# This is a basic workflow to help you get started with Actions

name: Hello Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: pwd
        run: pwd

      # Runs a set of commands using the runners shell
      - name: ls -al
        run: ls -al
